version: "2.1"

volumes:
  tailscale-state: {}

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile.template
    restart: always
    network_mode: host
    volumes:
      - tailscale-state:/tailscale
